sudo: required
services:
  - docker 

before_install:
  - docker build -t anthonylzh555/docker_react/frontend -f Dockerfile.dev . 

script:
  - docker run anthonylzh555/docker_react/frontend npm run test -- --coverage
  